### ISSUE TITLE
Projeto Final - Curso do dia 16/01/2017

### ISSUE THREAD

**Issue by DiegoPinho** [codeprestige/curso-introducaoreact#1]
**Entrega do projeto final**

Entregue nesta _issue_ o seu projeto final. Se você já tiver familiaridade com o Git, nos envie o link para o seu repositório. Caso contrário, apenas suba o projeto em alguma serviço de hospedagem na nuvem (Dropbox, Google Drive, etc) em um zip e nos forneça o link.

Se o seu projeto for aprovado, você poderá gerar o certificado [aqui](https://cp-certificates.herokuapp.com/).

**Observações do Instrutor**

- **Não** comite/armazene a pasta node_modules/. Isso torna o projeto desnecessariamente pesado.

**Comment by DiegoPinho** [comment]
**Thiago Deluca** - thiagodeluca@gmail.com
https://github.com/thiagodeluca/react_codeprestige

**Comment by lucianotvv** [comment]
Luciano Verde - lucianotvv@gmail.com
https://drive.google.com/drive/folders/1uE-c5Kgo_kA4IQ0dMXK3wwKnwkoN4vgA

**Comment by DiegoPinho** [comment]
**Jackson Santos** - jacksonjrs@gmail.com
https://github.com/jacksonjrs/react-code-prestige
