### ISSUE TITLE
Projeto Final - Curso do dia 06/02/2018

### ISSUE THREAD

**Issue by DiegoPinho** [codeprestige/curso-introducaoreact#4]
**Entrega do projeto final**

Entregue os comentário desta _issue_ o seu projeto final. Se você já tiver familiaridade com o Git, nos envie o link para o seu repositório. Caso contrário, apenas suba o projeto em alguma serviço de hospedagem na nuvem (Dropbox, Google Drive, etc) em um zip e nos forneça o link.

Se o seu projeto for aprovado, você poderá gerar o certificado [aqui](https://cp-certificates.herokuapp.com/).

**Observações do Instrutor**

- **Não** comite/armazene a pasta node_modules/. Isso torna o projeto desnecessariamente pesado.

**Comment by rafaelfez** [comment]
Segue meu projeto: https://github.com/rafaelfez/React_CodePrestigie muito obrigado por compartilhar o conhecimento Diego, React é fod*!
